server.port=8082
spring.application.name=auth-service

keycloak.auth-server-url=http://localhost:8081
keycloak.realm=workflow-realm
keycloak.resource=workflow-client
keycloak.credentials.secret=verybigsecret

jwt.auth.converter.resource-id=workflow-client
jwt.auth.converter.principle-attribute=preferred_username

spring.mongodb.uri=mongodb://root:password@localhost:27017/wfdb?authSource=admin

app.redirect-uri=http://localhost:8082/auth/callback

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/workflow-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/workflow-realm/protocol/openid-connect/certs

logging.file.name=temp/logs/auth-service.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7

