plugins {
    id 'java'
    id 'org.springframework.boot'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    implementation project(':security-commons')
    implementation project(':user-service')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-graphql'
    implementation("io.micrometer:context-propagation")

    implementation 'com.graphql-java:graphql-java-extended-scalars:24.0'
    implementation 'org.modelmapper:modelmapper:3.2.6'
    implementation 'org.modelmapper:modelmapper-module-record:1.0.0'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-graphql-test'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
}