services:
  mongodb:
    image: mongo:8
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: wfdb
    volumes:
      - mongo_data:/data/db
      - ./seed.js:/docker-entrypoint-initdb.d/seed.js:ro

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    container_name: keycloak
    command: start-dev
    ports:
      - "8081:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    depends_on:
      - mongodb

volumes:
  mongo_data: