extend type Query {
    projects(first: Int, after: String): ProjectConnection!
    project(id: ID!): Project
}

extend type Mutation {
    createProject(input: CreateProjectInput!): Project!
    updateProject(id: ID!, input: UpdateProjectInput!): Project!
}

input UpdateProjectInput {
    name: String
    description: String
    isPrivate: Boolean
}

input CreateProjectInput {
    name: String!
    key: String!
    description: String
    isPrivate: Boolean
}

type ProjectEdge {
    cursor: String!
    node: Project!
}

type ProjectConnection {
    pageInfo: PageInfo!
    edges: [ProjectEdge!]!
}

type Project {
    id: ID!
    name: String!
    key: String!
    description: String
    statuses: [Status!]!
    createdAt: String!
    updatedAt: String!
    createdBy: User!
    modifiedBy: User!
    visibility: Visibility!
}

type Status {
    id: ID!
    name: String!
    color: String!
    category: StatusCategory!
    displayOrder: Int!
    allowedTransitionIds: [String!]!
    isDefault: Boolean!
}

enum StatusCategory {
    TODO
    IN_PROGRESS
    DONE
}

enum Visibility {
    PRIVATE
    PUBLIC
}