extend type Query {
    sprintBoard(projectId: ID!): Sprint
}

extend type Mutation {
    createSprint(projectId: ID!, input: CreateSprintInput): Sprint!
    updateSprint(id: ID!, input: UpdateSprintInput): Sprint!
    activate(id: ID!): Sprint!
    moveIssue(sprintId: ID!, input: MoveIssueInput): Sprint!
    removeIssue(issueId: ID!): Sprint!
}

input MoveIssueInput {
    issueId: ID!
    nextIssueId: ID
}

input CreateSprintInput {
    name: String!
    goal: String
    startDate: String
    endDate: String
}

input UpdateSprintInput {
    name: String
    goal: String
    startDate: String
    endDate: String
}

type Sprint {
    id: ID!
    name: String!
    goal: String
    startDate: String
    endDate: String
    project: Project!
    issues: [Issue!]!
    active: Boolean!
    createdAt: String!
    createdBy: User!
    updatedAt: String!
    modifiedBy: User!
}
