extend type Query {
    sprintBoard(projectId: ID!): Sprint
    sprints(projectId: ID!, page: Int, pageSize: Int): SprintPage!
}

extend type Mutation {
    createSprint(projectId: ID!, input: CreateSprintInput): Sprint!
    updateSprint(id: ID!, input: UpdateSprintInput): Sprint!
    activate(id: ID!): Sprint!
    moveToSprint(sprintId: ID!, input: MoveIssueInput!): Sprint!
    removeFromSprint(issueId: ID!): Sprint!
}

input MoveIssueInput {
    issueId: ID!
    nextIssueId: ID
}

input CreateSprintInput {
    name: String!
    goal: String
    startDate: String
    endDate: String
}

input UpdateSprintInput {
    name: String
    goal: String
    startDate: String
    endDate: String
}

type SprintPage {
    items: [Sprint!]!
    total: Int!
    page: Int!
    pageSize: Int!
}

type Sprint {
    id: ID!
    name: String!
    goal: String
    startDate: String
    endDate: String
    project: Project!
    issues: [Issue!]!
    state: SprintState!
    createdAt: String!
    createdBy: User!
    updatedAt: String!
    modifiedBy: User!
}

enum SprintState {
    ACTIVE
    OPEN
    CLOSED
}
