jwt.secret=VGhpcy1pcy1hLXZlcnktc2VjdXJlLXNlY3JldC1rZXktMTIzNDU2
jwt.expiration=1800000

spring.application.name=WorkflowManager

spring.datasource.url=jdbc:postgresql://localhost:5432/postgresdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=dbuser
spring.datasource.password=dbpassword

spring.graphql.graphiql.enabled=true

logging.level.root=WARN

logging.level.com.example.myapp=DEBUG

spring.graphql.cors.allowed-origins=http://localhost:5173
spring.graphql.cors.allowed-methods=GET,POST
spring.graphql.cors.max-age=1800s

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always

spring.jpa.defer-datasource-initialization=true

# Show SQL queries
spring.jpa.show-sql=true
