spring.application.name=WorkflowManager

jwt.secret=VGhpcy1pcy1hLXZlcnktc2VjdXJlLXNlY3JldC1rZXktMTIzNDU2
jwt.expiration=1800000

spring.graphql.graphiql.enabled=true
spring.graphql.cors.allowed-origins=http://localhost:5173
spring.graphql.cors.allowed-methods=GET,POST
spring.graphql.cors.max-age=1800s

spring.mongodb.uri=mongodb://localhost:27017/wfdb

logging.level.root=WARN
logging.level.com.example.myapp=DEBUG
