insert into tasks (title, status) values ('Implement user authentication flow', 'InProgress');
insert into tasks (title, status) values ('Fix login redirect bug on mobile devices', 'Closed');
insert into tasks (title, status) values ('Design database schema for orders', 'Open');
insert into tasks (title, status) values ('Add unit tests for payment service', 'InProgress');
insert into tasks (title, status) values ('Optimize API response time', 'Open');
insert into tasks (title, status) values ('Refactor legacy user controller', 'Closed');
insert into tasks (title, status) values ('Integrate third-party email service', 'InProgress');
insert into tasks (title, status) values ('Create dashboard UI layout', 'Open');
insert into tasks (title, status) values ('Fix race condition in background job', 'InProgress');
insert into tasks (title, status) values ('Write documentation for deployment process', 'Closed');