spring.application.name=graphql-service

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.path=/graphql

spring.graphql.cors.allowed-origins=http://localhost:5173
spring.graphql.cors.allowed-methods=GET,POST
spring.graphql.cors.max-age=1800s

spring.mongodb.uri=mongodb://root:password@localhost:27017/wfdb?authSource=admin

jwt.auth.converter.resource-id=workflow-client
jwt.auth.converter.principle-attribute=preferred_username

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/workflow-realm

app.cors.allowed-origin=http://localhost:5173

logging.level.org.springframework.security=DEBUG
logging.level.com.sutusxxx.commons=DEBUG
logging.level.com.sutusxxx.graphql=DEBUG

logging.file.name=temp/logs/graphql-service.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7
